# Generated by Django 3.2.9 on 2021-12-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
