# Generated by Django 3.2.9 on 2021-12-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100, verbose_name='Family Relationship')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='family.member', verbose_name='Family Member')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.member', verbose_name='member')),
                ('relatives', models.ManyToManyField(related_name='family_members', to='family.Relative', verbose_name='relatives')),
            ],
        ),
    ]
