# Generated by Django 3.2.9 on 2021-12-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_familymember_familyrelation_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='FamilyRelation',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
