# Generated by Django 3.2.9 on 2021-12-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_familymember_familyrelationship_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='FamilyRelationship',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
