# Generated by Django 3.2.9 on 2021-12-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_familymember_familyrelationship_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='FamilyRelationship',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
