# Generated by Django 4.0 on 2021-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0011_person_relatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relatives',
            field=models.ManyToManyField(through='family.FamilyMember', to='family.Person', verbose_name='relatives'),
        ),
    ]
