# Generated by Django 3.2.9 on 2021-12-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20211205_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='lanugages',
            new_name='languages',
        ),
    ]
